# Generated by Django 5.2.7 on 2025-10-31 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_record'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='work_day',
            field=models.CharField(default='пн, ср, пт', verbose_name='Рабочие дни недели'),
        ),
    ]
